package com.homeguard.homeguard_api.service;

import com.homeguard.homeguard_api.dto.PersonEmbeddingDto;
import com.homeguard.homeguard_api.dto.PersonRequestDto;
import com.homeguard.homeguard_api.dto.PersonResponseDto;
import com.homeguard.homeguard_api.model.HomePerson;
import com.homeguard.homeguard_api.model.Person;
import com.homeguard.homeguard_api.repository.HomePersonRepository;
import com.homeguard.homeguard_api.repository.PersonRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional
@Slf4j
public class PersonService {
    
    private final PersonRepository personRepository;
    private final HomePersonRepository homePersonRepository;
    private final MLServiceClient mlServiceClient;
    
    public PersonResponseDto createPerson(PersonRequestDto request) {
        Person person = new Person();
        person.setId(UUID.randomUUID().toString());
        person.setName(request.getName());
        person.setPhone(request.getPhone());
        person.setEmail(request.getEmail());
        person.setPersonType(request.getPersonType());
        person.setNotes(request.getNotes());
        person.setProfileImagePath(request.getProfileImagePath());
        person.setIsActive(true);
        person.setCreatedAt(LocalDateTime.now());
        person.setUpdatedAt(LocalDateTime.now());
        
        // Save person first to get the ID
        Person savedPerson = personRepository.save(person);
        
        // Generate face embeddings if images are provided
        if (request.getFaceImageUrls() != null && !request.getFaceImageUrls().isEmpty()) {
            try {
                log.info("Generating face embeddings for newly created person {} with {} images", 
                        savedPerson.getId(), request.getFaceImageUrls().size());
                log.info("Image URLs: {}", request.getFaceImageUrls());
                
                // Update processing status
                savedPerson.setFaceProcessingStatus("PROCESSING");
                savedPerson.setFaceImageCount(request.getFaceImageUrls().size());
                savedPerson.setFaceProcessingError(null);
                savedPerson = personRepository.save(savedPerson);
                
                // Check if ML service is healthy
                if (mlServiceClient.isHealthy()) {
                    // Generate face embeddings
                    List<List<Double>> embeddings = mlServiceClient.generateFaceEmbeddings(
                        savedPerson.getId(), 
                        request.getFaceImageUrls()
                    );
                    
                    if (embeddings != null && !embeddings.isEmpty()) {
                        // Convert embeddings to JSON string
                        String faceVectorJson = mlServiceClient.embeddingsToJson(embeddings);
                        
                        if (faceVectorJson != null) {
                            savedPerson.setFaceVector(faceVectorJson);
                            savedPerson.setFaceProcessingStatus("COMPLETED");
                            savedPerson.setFaceEmbeddingsGeneratedAt(LocalDateTime.now());
                            savedPerson.setUpdatedAt(LocalDateTime.now());
                            
                            // Save updated person with face embeddings
                            savedPerson = personRepository.save(savedPerson);
                            log.info("Successfully generated and stored {} face embeddings for person {}", 
                                    embeddings.size(), savedPerson.getId());
                        } else {
                            log.error("Failed to convert embeddings to JSON for person {}", savedPerson.getId());
                            savedPerson.setFaceProcessingStatus("FAILED");
                            savedPerson.setFaceProcessingError("Failed to convert embeddings to JSON");
                            savedPerson = personRepository.save(savedPerson);
                        }
                    } else {
                        log.warn("No face embeddings generated for person {}", savedPerson.getId());
                        savedPerson.setFaceProcessingStatus("FAILED");
                        savedPerson.setFaceProcessingError("No face embeddings generated by ML service");
                        savedPerson = personRepository.save(savedPerson);
                    }
                } else {
                    log.warn("ML service is not healthy, skipping face embedding generation for person {}", 
                            savedPerson.getId());
                    savedPerson.setFaceProcessingStatus("FAILED");
                    savedPerson.setFaceProcessingError("ML service is not healthy");
                    savedPerson = personRepository.save(savedPerson);
                }
            } catch (Exception e) {
                log.error("Error generating face embeddings for person {}: {}", 
                        savedPerson.getId(), e.getMessage(), e);
                // Update status to failed
                savedPerson.setFaceProcessingStatus("FAILED");
                savedPerson.setFaceProcessingError(e.getMessage());
                savedPerson = personRepository.save(savedPerson);
                // Don't fail person creation if face embedding generation fails
            }
        }
        
        return mapToResponseDto(savedPerson);
    }
    
    public PersonResponseDto getPersonById(String id) {
        Person person = personRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Person not found"));
        return mapToResponseDto(person);
    }
    
    public List<PersonResponseDto> getAllActivePersons() {
        return personRepository.findByIsActiveTrue()
            .stream()
            .map(this::mapToResponseDto)
            .collect(Collectors.toList());
    }
    
    public PersonResponseDto updatePerson(String id, PersonRequestDto request) {
        Person person = personRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Person not found"));
        
        // Update fields only if they are provided (not null)
        if (request.getName() != null) {
            person.setName(request.getName());
        }
        if (request.getPhone() != null) {
            person.setPhone(request.getPhone());
        }
        if (request.getEmail() != null) {
            person.setEmail(request.getEmail());
        }
        if (request.getPersonType() != null) {
            person.setPersonType(request.getPersonType());
        }
        if (request.getNotes() != null) {
            person.setNotes(request.getNotes());
        }
        if (request.getProfileImagePath() != null) {
            person.setProfileImagePath(request.getProfileImagePath());
        }
        
        person.setUpdatedAt(LocalDateTime.now());
        
        Person savedPerson = personRepository.save(person);
        return mapToResponseDto(savedPerson);
    }
    
    public void deletePerson(String id) {
        Person person = personRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Person not found"));
        
        // Soft delete the person
        person.setIsActive(false);
        person.setUpdatedAt(LocalDateTime.now());
        
        // Cascade soft delete to all related HomePerson relationships
        if (person.getHomePersons() != null) {
            person.getHomePersons().forEach(homePerson -> {
                homePerson.setIsActive(false);
                homePerson.setUpdatedAt(LocalDateTime.now());
            });
        }
        
        // Cascade soft delete to all related RFID cards
        if (person.getRfidCards() != null) {
            person.getRfidCards().forEach(rfidCard -> {
                rfidCard.setIsActive(false);
                rfidCard.setUpdatedAt(LocalDateTime.now());
            });
        }
        
        personRepository.save(person);
        
        // Note: Profile images are kept for audit purposes in soft deletion
        // If you need to clean up images, you can add logic here to move them to a deleted folder
        // or mark them for cleanup in a background job
    }
    
    public PersonResponseDto uploadPersonImage(String id, MultipartFile image) {
        Person person = personRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Person not found"));
        
        // TODO: Implement image upload logic
        // For now, just set a placeholder path
        String imagePath = "/uploads/persons/" + id + "/" + image.getOriginalFilename();
        person.setProfileImagePath(imagePath);
        person.setUpdatedAt(LocalDateTime.now());
        
        Person savedPerson = personRepository.save(person);
        return mapToResponseDto(savedPerson);
    }
    
    public List<PersonResponseDto> getPersonsByHomeId(String homeId) {
        // Get all active HomePerson relationships for this home
        List<HomePerson> homePersons = homePersonRepository.findByHomeIdAndIsActiveTrue(homeId);
        
        // Extract person IDs and fetch persons
        List<String> personIds = homePersons.stream()
                .map(hp -> hp.getPerson().getId())
                .collect(Collectors.toList());
        
        // Fetch all persons by their IDs
        List<Person> persons = personRepository.findAllById(personIds);
        
        // Map to DTOs
        return persons.stream()
                .filter(Person::getIsActive)
                .map(this::mapToResponseDto)
                .collect(Collectors.toList());
    }
    
    /**
     * Get face embeddings for all persons in a home
     * Returns only persons who have embeddings generated
     */
    public List<PersonEmbeddingDto> getPersonEmbeddingsByHomeId(String homeId) {
        // Get all active HomePerson relationships for this home
        List<HomePerson> homePersons = homePersonRepository.findByHomeIdAndIsActiveTrue(homeId);
        
        // Extract person IDs and fetch persons
        List<String> personIds = homePersons.stream()
                .map(hp -> hp.getPerson().getId())
                .collect(Collectors.toList());
        
        // Fetch all persons by their IDs
        List<Person> persons = personRepository.findAllById(personIds);
        
        // Filter to only persons with embeddings and map to DTO
        return persons.stream()
                .filter(p -> p.getIsActive() && p.getFaceVector() != null && !p.getFaceVector().isEmpty())
                .map(p -> {
                    PersonEmbeddingDto dto = new PersonEmbeddingDto();
                    dto.setPersonId(p.getId());
                    dto.setName(p.getName());
                    dto.setFaceVector(p.getFaceVector());
                    return dto;
                })
                .collect(Collectors.toList());
    }
    
    /**
     * Generate face embeddings for a person from their image URLs
     * 
     * @param id Person ID
     * @param imageUrls List of Supabase image URLs
     * @return Updated person response
     */
    public PersonResponseDto generateFaceEmbeddings(String id, List<String> imageUrls) {
        Person person = personRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Person not found"));
        
        try {
            log.info("Generating face embeddings for person {} with {} images", id, imageUrls.size());
            
            // Check if ML service is healthy
            if (!mlServiceClient.isHealthy()) {
                log.warn("ML service is not healthy, skipping face embedding generation for person {}", id);
                return mapToResponseDto(person);
            }
            
            // Generate face embeddings
            List<List<Double>> embeddings = mlServiceClient.generateFaceEmbeddings(id, imageUrls);
            
            if (embeddings != null && !embeddings.isEmpty()) {
                // Convert embeddings to JSON string
                String faceVectorJson = mlServiceClient.embeddingsToJson(embeddings);
                
                if (faceVectorJson != null) {
                    person.setFaceVector(faceVectorJson);
                    person.setUpdatedAt(LocalDateTime.now());
                    
                    Person savedPerson = personRepository.save(person);
                    log.info("Successfully generated and stored {} face embeddings for person {}", 
                            embeddings.size(), id);
                    
                    return mapToResponseDto(savedPerson);
                } else {
                    log.error("Failed to convert embeddings to JSON for person {}", id);
                }
            } else {
                log.warn("No face embeddings generated for person {}", id);
            }
            
        } catch (Exception e) {
            log.error("Error generating face embeddings for person {}: {}", id, e.getMessage(), e);
        }
        
        return mapToResponseDto(person);
    }
    
    private PersonResponseDto mapToResponseDto(Person person) {
        PersonResponseDto dto = new PersonResponseDto();
        dto.setId(person.getId());
        dto.setName(person.getName());
        dto.setPhone(person.getPhone());
        dto.setEmail(person.getEmail());
        dto.setPersonType(person.getPersonType());
        dto.setProfileImagePath(person.getProfileImagePath());
        dto.setIsActive(person.getIsActive());
        dto.setLastSeen(person.getLastSeen());
        dto.setNotes(person.getNotes());
        dto.setCreatedAt(person.getCreatedAt());
        dto.setUpdatedAt(person.getUpdatedAt());
        return dto;
    }
}
